#!/usr/bin/env bash
set -Eeuo pipefail

BASE_DIR=${CONTAINER_RESTIC_BASE:-/root/container-restic}
GLOBAL_ENV="$BASE_DIR/restic.env"
CONTAINERS_DIR="$BASE_DIR/containers.d"
STATE_DIR="$BASE_DIR/state"
RESTORE_DIR="$BASE_DIR/restores"
LOCK_FILE="$BASE_DIR/.lock"

usage() {
  cat <<'EOF'
Usage: container-restic.sh <command> [args]

Commands:
  init                         Create directories and a restic.env template
  discover                     Generate/update one config per running Docker container
  backup <container|config>    Backup one configured container
  backup-all                   Backup every enabled config
  snapshots [container]        List snapshots, optionally for one container
  restore <container> <snap>   Restore one container snapshot to the staging dir
  forget                       Apply retention policy to this node's snapshots
  check                        Run restic repository check
  copy-secondary               Copy this node snapshots to secondary repository
  backup-github-config         Push scripts and sanitized config to GitHub
  list-configs                 Print enabled/disabled container configs

Environment:
  CONTAINER_RESTIC_BASE        Defaults to /root/container-restic
EOF
}

log() { printf '[%s] %s\n' "$(date '+%F %T')" "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

quote_env() {
  local s=${1-}
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '"%s"' "$s"
}

safe_name() {
  printf '%s' "$1" | tr -c 'A-Za-z0-9_.@+-' '_'
}

init_dirs() {
  install -d -m 0700 "$BASE_DIR" "$CONTAINERS_DIR" "$STATE_DIR" "$RESTORE_DIR"
  if [[ ! -f "$GLOBAL_ENV" ]]; then
    local host
    host=$(hostname -s 2>/dev/null || hostname || echo unknown)
    umask 077
    cat >"$GLOBAL_ENV" <<EOF
# Required. Examples:
#   RESTIC_REPOSITORY=s3:https://s3.example.com/bucket/prefix
#   RESTIC_REPOSITORY=sftp:user@backup.example.com:/srv/restic/$host
#   RESTIC_REPOSITORY=/mnt/backup/restic/$host
RESTIC_REPOSITORY=

# Required. Keep this file root-only.
RESTIC_PASSWORD_FILE=$BASE_DIR/restic-password

# Optional S3 variables, if RESTIC_REPOSITORY uses s3:...
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_DEFAULT_REGION=auto

NODE_NAME=$host
KEEP_DAILY=14
KEEP_WEEKLY=8
KEEP_MONTHLY=12
BACKUP_METADATA=1
RESTIC_PACK_SIZE=64
SECONDARY_RESTIC_REPOSITORY=
SECONDARY_RESTIC_PASSWORD_FILE=$BASE_DIR/restic-password
COPY_TO_SECONDARY_AFTER_BACKUP=0
GITHUB_CONFIG_BACKUP=0
GITHUB_OWNER=
GITHUB_REPO=
GITHUB_BRANCH=main
GITHUB_TOKEN=
GITHUB_PREFIX=container-restic
EOF
    printf '%s\n' "$(openssl rand -base64 36 2>/dev/null || date +%s%N)" >"$BASE_DIR/restic-password"
    chmod 0600 "$GLOBAL_ENV" "$BASE_DIR/restic-password"
    log "created $GLOBAL_ENV"
  fi
}

load_global_env() {
  [[ -f "$GLOBAL_ENV" ]] || die "missing $GLOBAL_ENV; run: $0 init"
  set -a
  # shellcheck disable=SC1090
  source "$GLOBAL_ENV"
  set +a
  [[ -n "${RESTIC_REPOSITORY:-}" ]] || die "RESTIC_REPOSITORY is empty in $GLOBAL_ENV"
  export RESTIC_REPOSITORY RESTIC_PASSWORD RESTIC_PASSWORD_FILE AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION SECONDARY_RESTIC_REPOSITORY SECONDARY_RESTIC_PASSWORD_FILE RCLONE_CONFIG GITHUB_OWNER GITHUB_REPO GITHUB_BRANCH GITHUB_TOKEN GITHUB_PREFIX
}

restic_base_args() {
  local args=()
  if [[ -n "${RESTIC_PACK_SIZE:-}" ]]; then
    args+=(--pack-size "$RESTIC_PACK_SIZE")
  fi
  printf '%s\0' "${args[@]}"
}

container_json() {
  local name=$1
  docker inspect "$name" | jq '.[0]'
}

discover_one() {
  local name=$1 json file tmp mounts compose_files workdir project service image
  json=$(container_json "$name")
  file="$CONTAINERS_DIR/$(safe_name "$name").env"
  tmp="$file.tmp"
  image=$(jq -r '.Config.Image // .Image // ""' <<<"$json")
  project=$(jq -r '.Config.Labels["com.docker.compose.project"] // ""' <<<"$json")
  service=$(jq -r '.Config.Labels["com.docker.compose.service"] // ""' <<<"$json")
  workdir=$(jq -r '.Config.Labels["com.docker.compose.project.working_dir"] // ""' <<<"$json")
  compose_files=$(jq -r '.Config.Labels["com.docker.compose.project.config_files"] // ""' <<<"$json")
  mounts=$(jq -r '[.Mounts[]? | select((.Type == "bind" or .Type == "volume") and (.Source // "") != "") | .Source] | unique | .[]' <<<"$json")
  local existing_excludes default_excludes
  existing_excludes=$(grep -E '^EXCLUDE_PATTERNS=' "$file" 2>/dev/null | tail -1 | cut -d= -f2- | sed 's/^"//;s/"$//' || true)
  default_excludes=""
  if [[ "$name" == "nodepanel" ]]; then
    default_excludes=$'/var/lib/nodepanel/backups\n/var/lib/nodepanel/assets'
  fi

  {
    printf '# Generated by container-restic.sh discover at %s\n' "$(date -Is)"
    printf 'ENABLED=%s\n' "$(grep -E '^ENABLED=' "$file" 2>/dev/null | tail -1 | cut -d= -f2- || echo 1)"
    printf 'CONTAINER_NAME=%s\n' "$(quote_env "$name")"
    printf 'PROJECT=%s\n' "$(quote_env "$project")"
    printf 'SERVICE=%s\n' "$(quote_env "$service")"
    printf 'IMAGE=%s\n' "$(quote_env "$image")"
    printf 'COMPOSE_WORKDIR=%s\n' "$(quote_env "$workdir")"
    printf 'COMPOSE_FILES=%s\n' "$(quote_env "$compose_files")"
    printf 'EXTRA_PATHS=%s\n' "$(quote_env "")"
    printf 'EXCLUDE_PATTERNS=%s\n' "$(quote_env "${existing_excludes:-$default_excludes}")"
    printf 'PRE_BACKUP_CMD=%s\n' "$(quote_env "")"
    printf 'POST_BACKUP_CMD=%s\n' "$(quote_env "")"
    printf 'NOTES=%s\n' "$(quote_env "")"
    printf 'MOUNT_PATHS=%s\n' "$(quote_env "$mounts")"
  } >"$tmp"
  chmod 0600 "$tmp"
  mv "$tmp" "$file"
  log "discovered $name -> $file"
}

cmd_discover() {
  need_cmd docker
  need_cmd jq
  init_dirs
  local names=()
  while IFS= read -r n; do names+=("$n"); done < <(docker ps --format '{{.Names}}' | sort)
  [[ ${#names[@]} -gt 0 ]] || die "no running containers found"
  local n
  for n in "${names[@]}"; do discover_one "$n"; done
}

config_file_for() {
  local key=$1
  if [[ -f "$key" ]]; then
    printf '%s\n' "$key"
    return
  fi
  local f="$CONTAINERS_DIR/$(safe_name "$key").env"
  [[ -f "$f" ]] || die "container config not found: $key"
  printf '%s\n' "$f"
}

load_container_env() {
  local file=$1
  CONTAINER_NAME= PROJECT= SERVICE= IMAGE= COMPOSE_WORKDIR= COMPOSE_FILES= EXTRA_PATHS= EXCLUDE_PATTERNS= PRE_BACKUP_CMD= POST_BACKUP_CMD= MOUNT_PATHS= ENABLED=1 NOTES=
  # shellcheck disable=SC1090
  source "$file"
  [[ -n "${CONTAINER_NAME:-}" ]] || die "CONTAINER_NAME missing in $file"
}

metadata_dir_for() {
  local name=$1 stamp=$2 dir
  dir="$STATE_DIR/metadata/$(safe_name "$name")/$stamp"
  install -d -m 0700 "$dir"
  printf '%s\n' "$dir"
}

write_metadata() {
  local dir=$1 name=$2 cfg=$3
  docker inspect "$name" >"$dir/docker-inspect.json"
  cp -f "$cfg" "$dir/container.env"
  if [[ -n "${COMPOSE_WORKDIR:-}" && -d "$COMPOSE_WORKDIR" ]]; then
    mkdir -p "$dir/compose"
    printf '%s\n' "$COMPOSE_WORKDIR" >"$dir/compose/working_dir.txt"
    local f abs
    IFS=',' read -r -a compose_arr <<<"${COMPOSE_FILES:-}"
    for f in "${compose_arr[@]}"; do
      [[ -n "$f" ]] || continue
      abs="$f"
      [[ "$abs" = /* ]] || abs="$COMPOSE_WORKDIR/$abs"
      if [[ -f "$abs" ]]; then
        install -m 0600 "$abs" "$dir/compose/$(basename "$abs")"
      fi
    done
    for f in .env env; do
      if [[ -f "$COMPOSE_WORKDIR/$f" ]]; then
        install -m 0600 "$COMPOSE_WORKDIR/$f" "$dir/compose/$f"
      fi
    done
  fi
  jq -n \
    --arg container "$name" \
    --arg node "${NODE_NAME:-$(hostname -s)}" \
    --arg project "${PROJECT:-}" \
    --arg service "${SERVICE:-}" \
    --arg image "${IMAGE:-}" \
    --arg created_at "$(date -Is)" \
    '{container:$container,node:$node,project:$project,service:$service,image:$image,created_at:$created_at}' \
    >"$dir/manifest.json"
}

paths_for_backup() {
  local meta_dir=$1
  printf '%s\0' "$meta_dir"
  local p
  while IFS= read -r p; do
    [[ -n "$p" && -e "$p" ]] && printf '%s\0' "$p"
  done <<<"${MOUNT_PATHS:-}"
  while IFS= read -r p; do
    [[ -n "$p" && -e "$p" ]] && printf '%s\0' "$p"
  done <<<"${EXTRA_PATHS:-}"
}

exclude_args() {
  local p
  while IFS= read -r p; do
    [[ -n "$p" ]] && printf '%s\0%s\0' '--exclude' "$p"
  done <<<"${EXCLUDE_PATTERNS:-}"
}

cmd_backup() {
  local cfg name stamp meta tags=() path_args=() excl_args=() restic_args=()
  [[ $# -eq 1 ]] || die "backup requires <container|config>"
  cfg=$(config_file_for "$1")
  load_global_env
  load_container_env "$cfg"
  [[ "${ENABLED:-1}" = "1" ]] || { log "skip disabled $CONTAINER_NAME"; return 0; }
  need_cmd docker
  need_cmd jq
  need_cmd restic
  docker inspect "$CONTAINER_NAME" >/dev/null || die "container not found: $CONTAINER_NAME"

  stamp=$(date '+%Y%m%d-%H%M%S')
  meta=$(metadata_dir_for "$CONTAINER_NAME" "$stamp")
  write_metadata "$meta" "$CONTAINER_NAME" "$cfg"

  if [[ -n "${PRE_BACKUP_CMD:-}" ]]; then
    log "pre-backup $CONTAINER_NAME"
    bash -lc "$PRE_BACKUP_CMD"
  fi

  while IFS= read -r -d '' p; do path_args+=("$p"); done < <(paths_for_backup "$meta")
  while IFS= read -r -d '' p; do excl_args+=("$p"); done < <(exclude_args)
  while IFS= read -r -d '' p; do restic_args+=("$p"); done < <(restic_base_args)

  [[ ${#path_args[@]} -gt 1 ]] || log "warning: $CONTAINER_NAME has no existing mount/extra paths; metadata-only backup"

  tags=(--tag "type:docker-container" --tag "node:${NODE_NAME:-$(hostname -s)}" --tag "container:$CONTAINER_NAME")
  [[ -n "${PROJECT:-}" ]] && tags+=(--tag "project:$PROJECT")
  [[ -n "${SERVICE:-}" ]] && tags+=(--tag "service:$SERVICE")

  log "backup $CONTAINER_NAME (${#path_args[@]} paths)"
  restic "${restic_args[@]}" backup "${path_args[@]}" "${tags[@]}" "${excl_args[@]}"

  if [[ -n "${POST_BACKUP_CMD:-}" ]]; then
    log "post-backup $CONTAINER_NAME"
    bash -lc "$POST_BACKUP_CMD"
  fi
}

cmd_backup_all() {
  init_dirs
  load_global_env
  local cfg enabled name failures=0
  shopt -s nullglob
  for cfg in "$CONTAINERS_DIR"/*.env; do
    enabled=$(grep -E '^ENABLED=' "$cfg" | tail -1 | cut -d= -f2- || echo 1)
    name=$(grep -E '^CONTAINER_NAME=' "$cfg" | tail -1 | cut -d= -f2- | tr -d '"' || basename "$cfg")
    if [[ "$enabled" != "1" ]]; then
      log "skip disabled $name"
      continue
    fi
    if ! cmd_backup "$cfg"; then
      log "failed $name"
      failures=$((failures + 1))
    fi
  done
  if [[ $failures -eq 0 && "${COPY_TO_SECONDARY_AFTER_BACKUP:-0}" = "1" && -n "${SECONDARY_RESTIC_REPOSITORY:-}" ]]; then
    cmd_copy_secondary
  fi
  [[ $failures -eq 0 ]] || die "$failures backup(s) failed"
}

cmd_snapshots() {
  load_global_env
  need_cmd restic
  if [[ $# -ge 1 && -n "$1" ]]; then
    restic snapshots --tag "container:$1"
  else
    restic snapshots --tag "type:docker-container" --tag "node:${NODE_NAME:-$(hostname -s)}"
  fi
}

cmd_restore() {
  [[ $# -eq 2 ]] || die "restore requires <container> <snapshot-id|latest>"
  load_global_env
  need_cmd restic
  local container=$1 snap=$2 target
  target="$RESTORE_DIR/$(safe_name "$container")/$snap"
  install -d -m 0700 "$target"
  if [[ "$snap" = "latest" ]]; then
    log "restore latest snapshot for $container -> $target"
    restic restore latest --tag "container:$container" --target "$target"
  else
    log "restore $snap for $container -> $target"
    restic restore "$snap" --target "$target"
  fi
  log "restored to $target"
  log "review the restored metadata directory before copying data back in-place"
}

cmd_forget() {
  load_global_env
  need_cmd restic
  restic forget \
    --tag "type:docker-container" \
    --tag "node:${NODE_NAME:-$(hostname -s)}" \
    --group-by tags \
    --keep-daily "${KEEP_DAILY:-14}" \
    --keep-weekly "${KEEP_WEEKLY:-8}" \
    --keep-monthly "${KEEP_MONTHLY:-12}" \
    --prune
}

cmd_check() {
  load_global_env
  need_cmd restic
  restic check
}

cmd_list_configs() {
  init_dirs
  shopt -s nullglob
  local cfg enabled name project service
  for cfg in "$CONTAINERS_DIR"/*.env; do
    enabled=$(grep -E '^ENABLED=' "$cfg" | tail -1 | cut -d= -f2- || echo 1)
    name=$(grep -E '^CONTAINER_NAME=' "$cfg" | tail -1 | cut -d= -f2- | sed 's/^"//;s/"$//' || basename "$cfg")
    project=$(grep -E '^PROJECT=' "$cfg" | tail -1 | cut -d= -f2- | sed 's/^"//;s/"$//' || true)
    service=$(grep -E '^SERVICE=' "$cfg" | tail -1 | cut -d= -f2- | sed 's/^"//;s/"$//' || true)
    printf '%s\t%s\t%s\t%s\n' "$enabled" "$name" "$project" "$service"
  done
}

main() {
  local cmd=${1:-}
  [[ -n "$cmd" ]] || { usage; exit 1; }
  shift || true
  case "$cmd" in
    init) init_dirs ;;
    discover) cmd_discover "$@" ;;
    backup) flock -n "$LOCK_FILE" bash -c '"$0" _backup_unlocked "$@"' "$0" "$@" ;;
    _backup_unlocked) cmd_backup "$@" ;;
    backup-all) flock -n "$LOCK_FILE" bash -c '"$0" _backup_all_unlocked "$@"' "$0" "$@" ;;
    _backup_all_unlocked) cmd_backup_all "$@" ;;
    snapshots) cmd_snapshots "$@" ;;
    restore) cmd_restore "$@" ;;
    forget) flock -n "$LOCK_FILE" bash -c '"$0" _forget_unlocked "$@"' "$0" "$@" ;;
    _forget_unlocked) cmd_forget "$@" ;;
    check) cmd_check "$@" ;;
    list-configs) cmd_list_configs "$@" ;;
    -h|--help|help) usage ;;
    *) usage; die "unknown command: $cmd" ;;
  esac
}

main "$@"
